name = "projectrc"
main = "src/index.ts"
compatibility_date = "2023-08-20"

[vars]

[env.staging]
name = "projectrc-staging"
vars = { ENVIRONMENT = "staging" }
routes = [
  { pattern = "staging.cron.projectrc.luxass.dev", custom_domain = true },
]

[env.production]
name = "projectrc"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "cron.projectrc.luxass.dev", custom_domain = true },
]

[triggers]
crons = [ "0 0 * * *" ]
