packages:
  - apps/*
  - packages/*
catalog:
  "@cloudflare/vitest-pool-workers": ^0.7.4
  "@cloudflare/workers-types": ^4.20250224.0
  "@hono/zod-openapi": ^0.19.0
  "@luxass/eslint-config": ^4.15.0
  "@octokit/core": ^6.1.4
  "@octokit/graphql": ^8.2.1
  "@octokit/plugin-paginate-rest": ^11.4.3
  "@scalar/hono-api-reference": ^0.5.177
  "@types/semver": ^7.5.8
  eslint: ^9.21.0
  eslint-plugin-format: ^1.0.1
  github-schema: ^1.14.0
  hono: ^4.7.2
  semver: ^7.7.1
  typescript: ^5.8.2
  vitest: 3.0.7
  wrangler: ^3.111.0
  zod: ^3.24.2
