packages:
  - apps/*
  - packages/*
catalog:
  "@cloudflare/vitest-pool-workers": ^0.6.15
  "@cloudflare/workers-types": ^4.20250204.0
  "@hono/zod-openapi": ^0.18.4
  "@luxass/eslint-config": ^4.15.0
  "@octokit/core": ^6.1.4
  "@octokit/graphql": ^8.2.0
  "@octokit/plugin-paginate-rest": ^11.4.2
  "@scalar/hono-api-reference": ^0.5.173
  "@types/semver": ^7.5.8
  eslint: ^9.20.1
  eslint-plugin-format: ^1.0.1
  github-schema: ^1.14.0
  hono: ^4.7.1
  semver: ^7.7.1
  typescript: ^5.7.3
  vitest: 2.1.9
  wrangler: ^3.109.0
  zod: ^3.24.2
