packages:
  - apps/*
  - packages/*
catalog:
  "@cloudflare/vitest-pool-workers": ^0.5.36
  "@cloudflare/workers-types": ^4.20241205.0
  "@hono/zod-openapi": ^0.18.3
  "@luxass/eslint-config": ^4.14.0
  "@octokit/core": ^6.1.2
  "@octokit/graphql": ^8.1.1
  "@octokit/plugin-paginate-rest": ^11.3.6
  "@scalar/hono-api-reference": ^0.5.164
  "@types/semver": ^7.5.8
  eslint: ^9.17.0
  eslint-plugin-format: ^0.1.3
  github-schema: ^1.12.2
  hono: ^4.6.14
  semver: ^7.6.3
  typescript: ^5.7.2
  vitest: 2.1.8
  wrangler: ^3.95.0
  zod: ^3.24.1
