packages:
  - apps/*
  - packages/*
catalog:
  "@cloudflare/vitest-pool-workers": ^0.4.29
  "@cloudflare/workers-types": ^4.20240903.0
  "@hono/zod-openapi": ^0.16.0
  "@luxass/eslint-config": ^4.11.0
  "@octokit/core": ^6.1.2
  "@octokit/graphql": ^8.1.1
  "@octokit/plugin-paginate-rest": ^11.3.3
  "@scalar/hono-api-reference": ^0.5.144
  "@types/semver": ^7.5.8
  eslint: ^9.10.0
  eslint-plugin-format: ^0.1.2
  github-schema: ^1.10.5
  hono: ^4.5.11
  semver: ^7.6.3
  typescript: ^5.5.4
  vitest: 1.5.0
  wrangler: ^3.75.0
  zod: ^3.23.8
