packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    "@cloudflare/vitest-pool-workers": 0.10.0
    "@luxass/eslint-config": 5.3.2
    "@types/node": 22.18.12
    "@types/semver": 7.7.1
    eslint: ^9.29.0
    eslint-plugin-format: ^1.0.1
    github-schema: 1.20.17
    tsx: 4.20.6
    typescript: 5.9.3
    vitest: 3.2.4
    wrangler: 4.45.0
    "@cloudflare/workers-types": 4.20251014.0

  prod:
    "@hono/zod-openapi": 0.19.10
    "@octokit/core": 7.0.5
    "@octokit/graphql": 9.0.2
    "@octokit/plugin-paginate-rest": 13.2.1
    "@scalar/hono-api-reference": 0.9.22
    hono: 4.10.3
    semver: 7.7.3
    zod: 3.25.76

  vscode:
    "@ast-grep/napi": 0.39.6

  image:
    "@resvg/resvg-wasm": 2.4.1
    hono-jsx-to-react: 0.2.0
    satori: 0.18.3
    yoga-wasm-web: 0.3.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
