-- Migration number: 0001 	 2024-08-17T06:14:46.138Z
DROP TABLE IF EXISTS repositories;
CREATE TABLE IF NOT EXISTS repositories (
  id INTEGER PRIMARY KEY,
  github_id INTEGER NOT NULL UNIQUE,
  name_with_owner TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
