name = "assets"
main = "src/index.ts"
compatibility_date = "2024-12-15"

[observability.logs]
enabled = true

[env.preview]
name = "assets-preview"
vars = { ENVIRONMENT = "preview" }
routes = [
  { pattern = "preview.assets.luxass.dev", custom_domain = true },
  { pattern = "preview.assets.luxass.com", custom_domain = true },
]

[env.production]
name = "assets"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "assets.luxass.dev", custom_domain = true },
  { pattern = "assets.luxass.com", custom_domain = true },
]
