name = "vscode"
main = "src/index.ts"
compatibility_date = "2024-12-15"

[observability.logs]
enabled = true

[env.preview]
name = "vscode-preview"
vars = { ENVIRONMENT = "preview" }
routes = [ { pattern = "preview.vscode.luxass.dev", custom_domain = true } ]

[env.production]
name = "vscode"
vars = { ENVIRONMENT = "production" }
routes = [ { pattern = "vscode.luxass.dev", custom_domain = true } ]
