name = "mosaic"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]

# preview

[env.preview]
name = "mosaic-preview"
vars = { ENVIRONMENT = "preview" }
routes = [
  { pattern = "preview.mosaic-worker.luxass.dev", custom_domain = true },
  { pattern = "preview.mosaic-worker.luxass.com", custom_domain = true },
]
d1_databases = [ { binding = "DATABASE", database_name = "preview-mosaic", database_id = "c966c318-626f-45b8-96fa-45807d5174ee" } ]

[env.preview.triggers]
crons = [ "*/10 * * * *" ]

# production

[env.production]
name = "mosaic"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "worker.mosaic.luxass.dev", custom_domain = true },
  { pattern = "worker.mosaic.luxass.com", custom_domain = true },
]
d1_databases = [ { binding = "DATABASE", database_name = "prod-mosaic", database_id = "5b479f67-3311-4394-98c2-b983e7b29c53" } ]

[env.production.triggers]
crons = [ "*/10 * * * *" ]

# local

[[d1_databases]]
binding = "DATABASE"
database_name = "prod-mosaic"
database_id = "5b479f67-3311-4394-98c2-b983e7b29c53"
