name = "image"
main = "src/index.ts"
compatibility_date = "2024-12-15"

[observability.logs]
enabled = true

[env.preview]
name = "image-preview"
vars = { ENVIRONMENT = "preview" }
routes = [
  { pattern = "preview.image.luxass.dev", custom_domain = true },
  { pattern = "preview.image.luxass.com", custom_domain = true },
]

[env.production]
name = "image"
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "image.luxass.dev", custom_domain = true },
  { pattern = "image.luxass.com", custom_domain = true },
]
