name: deploy assets worker to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - "apps/assets/**"
      - ".github/workflows/assets-push-deploy.yaml"
      - ".github/workflows/deploy-worker.yaml"
      - "packages/**"
      - "pnpm-workspace.yaml"
      - "package.json"
      - "pnpm-lock.yaml"

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      app: assets
      environment: production
      dry_run: ${{ github.event.inputs.dry-run == 'true' }}
      build_command: pnpm build:assets
      lint_command: pnpm --filter "assets" run lint
      typecheck_command: pnpm --filter "assets" run typecheck
      test_command: pnpm --filter "assets" run test
