name: deploy assets worker to preview

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "apps/assets/**"
      - ".github/workflows/assets-pr-deploy.yaml"
      - ".github/workflows/deploy-worker.yaml"
      - "packages/**"
      - "pnpm-workspace.yaml"
      - "package.json"
      - "pnpm-lock.yaml"

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    with:
      app: assets
      environment: preview
      dry_run: ${{ github.event.inputs.dry-run == 'true' }}
      build_arg: build:assets
      lint_arg: --filter assets run lint
      typecheck_arg: --filter assets run typecheck
      test_arg: --filter assets run test
