name: deploy image worker to preview

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "apps/image/**"
      - ".github/workflows/image-pr-deploy.yaml"
      - ".github/workflows/reusable-deploy.yaml"
      - "packages/**"
      - "pnpm-workspace.yaml"
      - "package.json"
      - "pnpm-lock.yaml"

permissions: {}

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      app: image
      wrangler_environment: preview
      dry_run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['dry-run'] == 'true' }}
      build_arg: build:image
      typecheck_arg: --filter image run typecheck
