name: deploy image worker to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - "apps/image/**"
      - ".github/workflows/image-push-deploy.yaml"
      - ".github/workflows/deploy-worker.yaml"
      - "packages/**"
      - "pnpm-workspace.yaml"
      - "package.json"
      - "pnpm-lock.yaml"

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    with:
      app: image
      environment: production
      dry_run: ${{ github.event.inputs.dry-run == 'true' }}
      build_arg: build:image
      typecheck_arg: --filter image run typecheck
