name: deploy mosaic worker to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: "false"
  push:
    branches:
      - main
    paths:
      - "apps/mosaic/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.1.7

      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build:mosaic

      - name: lint
        run: pnpm --filter "mosaic" run lint

      - name: typecheck
        run: pnpm --filter "mosaic" run typecheck

      - name: test
        run: pnpm --filter "mosaic" run test

      - name: deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./apps/mosaic
          environment: production

      - name: run migrations
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./apps/mosaic
          environment: production
          command: d1 migrations apply prod-mosaic --remote --env production
