name: refresh worker in production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: "false"
      app:
        description: The app to deploy
        required: true
        default: assets
        type: choice
        options:
          - vscode
          - assets
          - image

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    name: refresh ${{ github.event.inputs.app }} worker in production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SELECTED_APP: ${{ github.event.inputs.app }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm --filter "$SELECTED_APP" run build

      - name: lint
        run: pnpm --filter "$SELECTED_APP" run lint

      - name: typecheck
        run: pnpm --filter "$SELECTED_APP" run typecheck

      - name: test
        run: pnpm --filter "$SELECTED_APP" run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: get directory
        id: get-directory
        run: echo "dir=./apps/$SELECTED_APP" >> "$GITHUB_OUTPUT"

      - name: deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3.13.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ steps.get-directory.outputs.dir }}
          environment: production
