name: refresh worker in production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: "false"
      app:
        description: The app to deploy
        required: true
        default: assets
        type: choice
        options:
          - assets
          - image

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy-assets:
    if: ${{ github.event.inputs.app == 'assets' }}
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      app: assets
      environment: production
      dry_run: ${{ github.event.inputs.dry-run == 'true' }}
      build_command: pnpm build:assets
      lint_command: pnpm --filter "assets" run lint
      typecheck_command: pnpm --filter "assets" run typecheck
      test_command: pnpm --filter "assets" run test

  deploy-image:
    if: ${{ github.event.inputs.app == 'image' }}
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      app: image
      environment: production
      dry_run: ${{ github.event.inputs.dry-run == 'true' }}
      build_command: pnpm build:image
      typecheck_command: pnpm --filter "image" run typecheck
