name: deploy worker

on:
  workflow_call:
    inputs:
      app:
        description: The app to deploy
        required: true
        type: string
      wrangler_environment:
        description: The Wrangler environment to deploy
        required: true
        type: string
      dry_run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
      build_arg:
        description: The pnpm args used to build the app
        required: true
        type: string
      typecheck_arg:
        description: The pnpm args used to typecheck the app
        required: true
        type: string
      test_arg:
        description: The pnpm args used to test the app
        required: false
        default: ""
        type: string
permissions: {}

jobs:
  deploy:
    name: deploy ${{ inputs.app }} worker to ${{ inputs.wrangler_environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.repository_owner == 'luxass'
    environment: deploy
    env:
      APP_DIRECTORY: ${{ format('./apps/{0}', inputs.app) }}
      BUILD_ARG: ${{ inputs.build_arg }}
      TYPECHECK_ARG: ${{ inputs.typecheck_arg }}
      TEST_ARG: ${{ inputs.test_arg }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          package-manager-cache: false

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm $BUILD_ARG

      - name: typecheck
        run: pnpm $TYPECHECK_ARG

      - name: test
        if: ${{ inputs.test_arg != '' }}
        run: pnpm $TEST_ARG
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: deploy
        if: ${{ !inputs.dry_run }}
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ env.APP_DIRECTORY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: ${{ inputs.wrangler_environment }}
