name: Update SVG Sources

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: update sources
        run: pnpm --filter "vscode" run "update:sources"

      - name: Lint with fix
        run: pnpm run lint --fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit-message: "feat(vscode): updated allowed svg sources"
          title: "feat(vscode): updated allowed svg sources"
          body: |
            I found some changes in the allowed svg sources for Visual Studio Marketplace

            I don't know what they changed, but I'm sure it's important.
            If you want you can go take a look yourself.

            I will be waiting for your approval 👋.

            This is an automated PR to update the Allowed SVG Sources.
          branch: vscode/update-svg-sources
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass
