name: deploy projectrc.worker to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: "false"
  push:
    branches:
      - main
    paths:
      - "apps/projectrc.worker/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:projectrc

      - name: Lint
        run: pnpm --filter "projectrc.worker" run lint

      - name: Typecheck
        run: pnpm --filter "projectrc.worker" run typecheck

      - name: Deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./apps/projectrc.worker
          environment: production
