name: deploy vscode.worker to staging

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: "false"
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "apps/vscode.worker/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:vscode

      - name: Lint
        run: pnpm --filter "vscode.worker" run lint

      - name: Typecheck
        run: pnpm --filter "vscode.worker" run typecheck

      - name: Deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./apps/vscode.worker
          environment: staging
