name: deploy vscode worker to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - "apps/vscode/**"

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.2.2

      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build:vscode

      - name: lint
        run: pnpm --filter "vscode" run lint

      - name: typecheck
        run: pnpm --filter "vscode" run typecheck

      - name: test
        run: pnpm --filter "vscode" run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: update vsce content
        run: pnpm --filter "vscode" run "update:vsce-content"

      - name: deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./apps/vscode
          environment: production
